name: Android
on:
  workflow_dispatch:
jobs:
  build:
    name: build flutter for Android
    runs-on: macos-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.3.2"
      WORKING_DIRECTORY: "./hello_flutter"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
        working-directory: ${{env.WORKING_DIRECTORY}}
      - run: flutter build apk
        working-directory: ${{env.WORKING_DIRECTORY}}     
      - name: Archive apk artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ${{env.WORKING_DIRECTORY}}/build/app/outputs/flutter-apk/app-release.apk
  release:
    name: release to firebase app distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        name: Download apk
        with:
          name: apk
          path: tmp/apk
      - run: ls -R
        working-directory: tmp/apk
      - name: Upload APK to Firebase App Distribution Action
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: tmp/apk/app-release.apk
          groups: testers