name: hello world
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "first job!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "second job!"